config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :shelves
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/search", to: "searches#google_books_search"

  patch "/reshelf", to: "books#reshelf"

  root "shelves#index"
end

app/controllers/shelves_controller.rb
# frozen_string_literal: true

class ShelvesController < ApplicationController
  before_action :set_shelf, only: %i[show edit update destroy]

  # GET /shelves or /shelves.json
  def index
    @shelves = Shelf.all
  end

  # GET /shelves/1 or /shelves/1.json
  def show; end

  # GET /shelves/new
  def new
    @shelf = Shelf.new
  end

  # GET /shelves/1/edit
  def edit; end

  # POST /shelves or /shelves.json
  def create
    @shelf = Shelf.new(shelf_params)

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to shelf_url(@shelf), notice: "Shelf was successfully created." }
        format.json { render :show, status: :created, location: @shelf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shelves/1 or /shelves/1.json
  def update
    respond_to do |format|
      if @shelf.update(shelf_params)
        format.html { redirect_to shelf_url(@shelf), notice: "Shelf was successfully updated." }
        format.json { render :show, status: :ok, location: @shelf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shelf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelves/1 or /shelves/1.json
  def destroy
    @shelf.destroy

    respond_to do |format|
      format.html { redirect_to shelves_url, notice: "Shelf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shelf
    @shelf = Shelf.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shelf_params
    params.require(:shelf).permit(:name)
  end
end

app/helpers/shelves_helper.rb
# frozen_string_literal: true

module ShelvesHelper
end

app/views/shelves/_form.html.erb
<%= form_with(model: shelf) do |form| %>
  <% if shelf.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shelf.errors.count, "error") %> prohibited this shelf from being saved:</h2>
      <ul>
        <% shelf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shelves/_shelved_book.html.erb
<div class="shelved-book">
  <%= link_to shelved_book do %>
    <img src=<%= shelved_book.image_links["thumbnail"] %> class="book-cover img-thumbnail">
    <div class="title-byline">
      <div class="title"><%= shelved_book.title %></div>
        <% shelved_book.authors.each_value do |author| %>
          <span class="authors-attribution">
            <%= author %>
          </span>
        <% end %>
    </div>
  <% end %>
</div>

app/views/shelves/edit.html.erb
<h1>Editing shelf</h1>

<%= render "form", shelf: @shelf %>

<br>

<div>
  <%= link_to "Show this shelf", @shelf %> |
  <%= link_to "Back to shelves", shelves_path %>
</div>

app/views/shelves/index.html.erb
<div id="shelves">
  <% @shelves.each do |shelf| %>
    <div class="shelf-identifier">
      <div class="shelf-name"><%= shelf.name.upcase %></div>
      <div class="shelf-flourish"></div>
    </div>
    <div class="shelf">
      <div class="scrollmenu">
        <% shelf.books.each do |shelved_book| %>
          <%= render partial: "shelved_book", object: shelved_book %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shelves/new.html.erb
<h1>New shelf</h1>

<%= render "form", shelf: @shelf %>

<br>

<div>
  <%= link_to "Back to shelves", shelves_path %>
</div>

app/views/shelves/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shelf %>

<div>
  <%= link_to "Edit this shelf", edit_shelf_path(@shelf) %> |
  <%= link_to "Back to shelves", shelves_path %>

  <%= button_to "Destroy this shelf", @shelf, method: :delete %>
</div>