config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :shelves
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/search", to: "searches#google_books_search"

  patch "/reshelf", to: "books#reshelf"

  root "shelves#index"
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  acts_as_tenant :user
  has_many :shelvings
  has_many :shelves, through: :shelvings

  validates :title, :subtitle, :authors, :description, :page_count, :categories, :image_links, presence: true
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy reshelf]
  after_action :add_to_shelf, only: %i[create]
  # GET /books
  def index
    @books = Book.all
  end

  # GET /books/1
  def show; end

  # POST /books
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to shelves_path, notice: "Book was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /books/1
  def reshelf
    shelf = Shelf.find(@book.shelves.first.id)
    @book.shelves.delete(shelf)

    @book.shelves << Shelf.find(params[:book][:shelf])
    redirect_to shelves_path
  end

  # DELETE /books/1
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Book was successfully destroyed." }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    permitted_params = params.require(:book).permit(:title, :subtitle, :description, :page_count,
                                                    authors: params["book"]["authors"].keys, categories: params["book"]["categories"].keys, image_links: params["book"]["image_links"].keys)
  end

  def add_to_shelf
    @shelf = Shelf.find(params[:shelf])
    @shelf.books << @book
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_search_results.html.erb
<% if @response %>
  <% @response["items"].each do |item| %>
    <%= item["volumeInfo"] %>
    <%= button_to("Add Book", :params => {
        :title => item["volumeInfo"]["title"],
        :subtitle => item["volumeInfo"]["subtitle"],
        :authors => item["volumeInfo"]["authors"],
        :description => item["volumeInfo"]["description"],
        :page_count => item["volumeInfo"]["pageCount"],
        :categories => item["volumeInfo"]["categories"],
        :image_link => item["volumeInfo"]["imageLinks"]["thumbnail"]
      })
      %>
    <hr>
  <% end %>
<% else %>
  No search results.
<% end %>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <h1><%= book.title %></h1>
    <h2><%= book.subtitle %></h2>
    <p><%= book.authors %></p>
    <p><%= book.categories %></p>
    <p><%= book.page_count %></p>
    <img src=<%= book.image_link%> >
    <%= button_to("Delete", book_path(book), :method => :delete) %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="book-container">
  <div class="thumbnail-shelving">
    <img src=<%= @book.image_links["thumbnail"] %> class="book-cover img-thumbnail">
    <%= form_with(model: @book, url: { action: "reshelf", params: {id: @book.id} }, :class => "shelf-select" ) do |form| %>
      <%= form.select('shelf', options_from_collection_for_select(Shelf.all, "id", "name", @book.shelves.first.id), {}, { :onchange => "this.form.submit();" }) %>
    <% end %>
    <%= button_to @book, method: :delete, :class => "delete-book" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>
  <div class="book-details">
    <h5 class="book-categories"><%= @book.categories.values.join(", ") %></h5>
    <h3 class="book-title"><i><%= @book.title %></i></h3>
    <h6><%= @book.authors.values.join(", ") %></h6>
    <hr>
    <h6>PUBLISHER'S DESCRIPTION</h6>
    <p class="book-description"><%= @book.description %></p>
  </div>
</div>