config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :shelves
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/search", to: "searches#google_books_search"

  patch "/reshelf", to: "books#reshelf"

  root "shelves#index"
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  require "google_api"

  def google_books_search
    @response = GoogleApi.new(params[:search]).query
  end
end

app/views/searches/google_books_search.html.erb
<% if @response %>
  <% @response["items"].each do |item| %>
    <% book = item["volumeInfo"]%>
    <%= book["title"] %> by <%= book["authors"]&.join(", ") %>

    <%= form_tag books_path do %>
      <%= select_tag('shelf', options_from_collection_for_select(Shelf.all, "id", "name")) %>
      <%= hidden_field(:book, :title, :value => book["title"]) %>
      <%= hidden_field(:book, :subtitle, :value => book["subtitle"]) %>
      <%= hidden_field(:book, :description, :value => book["description"]) %>
      <%= hidden_field(:book, :page_count, :value => book["pageCount"]) %>

      <% book["authors"]&.each_with_index do |author, index| %>
        <%= hidden_field(:book, "authors[#{index}]", :value => author) %>
      <% end %>

      <% book["categories"]&.each_with_index do |category, index| %>
        <%= hidden_field(:book, "categories[#{index}]", :value => category) %>
      <% end %>

      <% book["imageLinks"]&.each do |key,value| %>
        <%= hidden_field(:book, "image_links[#{key}]", :value => value) %>
      <% end %>

      <%= submit_tag "Create" %>
    <% end %>
    <hr>
  <% end %>
<% else %>
  No search results.
<% end %>